id: P004455
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W28876
  title: སྙན་རྩོམ་གཟི་མིག་དགུ་པ
  author: ''
  volumes:
    d564fc9c86dc4793b58bf1c48740110a:
      image_group_id: I4860
      title: ''
      volume_number: 1
      total_pages: 162
      base_file: v001.txt
